apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: active-mq
  name: active_mq
spec:
  ports:
    - name: "61613"
      port: 61613
      targetPort: 61613
  selector:
    io.kompose.service: active-mq
