services:
  marketplace:
    # build:
    #   context: .
    image: marketplace
    environment:
      SECRET_KEY_BASE: "secret_key_base"
      MP_DATABASE_HOST: db
      MP_DATABASE_USERNAME: mp
      MP_DATABASE_PASSWORD: mp
      MP_DATABASE_NAME: mp_development
      REDIS_URL: redis://redis:6379/0
      ELASTICSEARCH_URL: http://el:9200
      IMPORTER_AAI_BASE_URL: "https://your-aai-base-url.com"
      IMPORTER_AAI_REFRESH_TOKEN: "refresh-token"
      IMPORTER_AAI_CLIENT_ID: "client-id"
      # ROOT_URL: "http://0.0.0.0:5000"
      PORT: "5000"
    ports:
      - "5000:5000"
    networks:
      - mp-local
    entrypoint: ["./entrypoint.sh"]
  db:
    image: postgres:16.4
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - mp-local
    environment:
      POSTGRES_DB: ${DB_POSTGRES_DB:-mp}
      POSTGRES_USER: ${DB_POSTGRES_USER:-mp}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD:-mp}
  el:
    image: elasticsearch:7.8.0
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    networks:
      - mp-local
    environment:
      discovery.type: single-node
  redis:
    image: redis:7.2.4
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - mp-local
  active_mq:
    image: rmohr/activemq
    ports:
      - "127.0.0.1:61613:61613"
    networks:
      - mp-local

volumes:
  db-data:

networks:
  mp-local:
    driver: bridge

