apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
  labels:
    io.kompose.service: el
  name: el
spec:
  selector:
    io.kompose.service: el
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
    - name: "9300"
      port: 9300
      targetPort: 9300

