apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
  labels:
    io.kompose.service: marketplace
  name: marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: marketplace
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
      labels:
        io.kompose.service: marketplace
    spec:
      containers:
        - command:
            - /root/whitelabel-marketplace/entrypoint.sh
          env:
            - name: CHECKIN_HOST
              valueFrom:
                configMapKeyRef:
                  key: CHECKIN_HOST
                  name: env
            - name: CHECKIN_IDENTIFIER
              valueFrom:
                configMapKeyRef:
                  key: CHECKIN_IDENTIFIER
                  name: env
            - name: CHECKIN_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  key: CHECKIN_ISSUER_URI
                  name: env
            - name: CHECKIN_SCOPE
              valueFrom:
                configMapKeyRef:
                  key: CHECKIN_SCOPE
                  name: env
            - name: CHECKIN_SECRET
              valueFrom:
                configMapKeyRef:
                  key: CHECKIN_SECRET
                  name: env
            - name: ELASTICSEARCH_URL
              valueFrom:
                configMapKeyRef:
                  key: ELASTICSEARCH_URL
                  name: env
            - name: MP_DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  key: MP_DATABASE_HOST
                  name: env
            - name: MP_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  key: MP_DATABASE_NAME
                  name: env
            - name: MP_DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MP_DATABASE_PASSWORD
                  name: env
            - name: MP_DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: MP_DATABASE_USERNAME
                  name: env
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PORT
                  name: env
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  key: REDIS_URL
                  name: env
            - name: SECRET_KEY_BASE
              valueFrom:
                configMapKeyRef:
                  key: SECRET_KEY_BASE
                  name: env
          image: bermudea/marketplace
          name: marketplace
          ports:
            - containerPort: 5000
              protocol: TCP
          volumeMounts:
            - mountPath: /root/whitelabel-marketplace/entrypoint.sh
              name: marketplace-cm0
              subPath: entrypoint.sh
            - name: css-build
              mountPath: /root/whitelabel-marketplace/app/assets/builds/
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: entrypoint.sh
                path: entrypoint.sh
            name: marketplace-cm0
            defaultMode: 0755
          name: marketplace-cm0
        - name: css-build
          emptyDir: {}
