apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
  labels:
    io.kompose.service: active-mq
  name: active-mq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: active-mq
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
      labels:
        io.kompose.service: active-mq
    spec:
      containers:
        - image: rmohr/activemq
          name: active-mq
          ports:
            - containerPort: 61613
              protocol: TCP
      restartPolicy: Always
