apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
  labels:
    io.kompose.service: active-mq
  name: active-mq
spec:
  selector:
    io.kompose.service: active-mq
  ports:
    - name: "61613"
      port: 61613
      targetPort: 61613

